/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class index extends javax.swing.JFrame {

    BBDD_manager manager = new BBDD_manager();

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        component(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPlatform_frame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        name_addPlatform = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        price_addPlatform = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        date_addPlatform = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        id_addPlatform = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        addSerie_frame = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        name_addSerie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        director_addSerie = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        date_addSerie = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        id_addSerie = new javax.swing.JTextField();
        accept_addPlatform = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        platforma_comboBox_2 = new javax.swing.JComboBox<>();
        addMovie_frame = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        name_addMovie = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        director_addMovie = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        date_addMovie = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        id_addMovie = new javax.swing.JTextField();
        accept_addMovie = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        platforma_comboBox_3 = new javax.swing.JComboBox<>();
        connect = new javax.swing.JButton();
        disconnect = new javax.swing.JButton();
        platforma_comboBox_1 = new javax.swing.JComboBox<>();
        restore = new javax.swing.JButton();
        addPlatform_button = new javax.swing.JButton();
        findByPlatform = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        addSerie_button = new javax.swing.JButton();
        showSeries_button = new javax.swing.JButton();
        showMovies_button = new javax.swing.JButton();
        addMovie_button = new javax.swing.JButton();
        showPlatforms_button = new javax.swing.JButton();

        addPlatform_frame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        addPlatform_frame.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, 30));
        addPlatform_frame.getContentPane().add(name_addPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 140, 30));

        jLabel2.setText("Precio");
        addPlatform_frame.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));
        addPlatform_frame.getContentPane().add(price_addPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, 30));

        jLabel3.setText("Fecha salida(YYYY-MM-DD)");
        addPlatform_frame.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 30));
        addPlatform_frame.getContentPane().add(date_addPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 140, 30));

        jLabel4.setText("Id");
        addPlatform_frame.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 30));
        addPlatform_frame.getContentPane().add(id_addPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 140, 30));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        addPlatform_frame.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 310, -1));

        addSerie_frame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Nombre");
        addSerie_frame.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, 30));
        addSerie_frame.getContentPane().add(name_addSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 140, 30));

        jLabel6.setText("Plataforma");
        addSerie_frame.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 30));
        addSerie_frame.getContentPane().add(director_addSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, 30));

        jLabel7.setText("Fecha salida(YYYY-MM-DD)");
        addSerie_frame.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, 30));
        addSerie_frame.getContentPane().add(date_addSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 140, 30));

        jLabel8.setText("Id");
        addSerie_frame.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 30));
        addSerie_frame.getContentPane().add(id_addSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 140, 30));

        accept_addPlatform.setText("Aceptar");
        accept_addPlatform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept_addPlatformActionPerformed(evt);
            }
        });
        addSerie_frame.getContentPane().add(accept_addPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 310, -1));

        jLabel9.setText("Director");
        addSerie_frame.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));

        addSerie_frame.getContentPane().add(platforma_comboBox_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 140, 30));

        addMovie_frame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Nombre");
        addMovie_frame.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, 30));
        addMovie_frame.getContentPane().add(name_addMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 140, 30));

        jLabel11.setText("Plataforma");
        addMovie_frame.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 30));
        addMovie_frame.getContentPane().add(director_addMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, 30));

        jLabel12.setText("Fecha salida(YYYY-MM-DD)");
        addMovie_frame.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, 30));
        addMovie_frame.getContentPane().add(date_addMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 140, 30));

        jLabel13.setText("Id");
        addMovie_frame.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 30));
        addMovie_frame.getContentPane().add(id_addMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 140, 30));

        accept_addMovie.setText("Aceptar");
        accept_addMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept_addMovieActionPerformed(evt);
            }
        });
        addMovie_frame.getContentPane().add(accept_addMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 310, -1));

        jLabel14.setText("Director");
        addMovie_frame.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));

        addMovie_frame.getContentPane().add(platforma_comboBox_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 140, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 525));
        setPreferredSize(new java.awt.Dimension(850, 525));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        connect.setText("Conectar");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });
        getContentPane().add(connect, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        disconnect.setText("Desconectar");
        disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectActionPerformed(evt);
            }
        });
        getContentPane().add(disconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        getContentPane().add(platforma_comboBox_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 30));

        restore.setText("Restaurar base de datos");
        restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreActionPerformed(evt);
            }
        });
        getContentPane().add(restore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, -1));

        addPlatform_button.setText("Añadir plataforma");
        addPlatform_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlatform_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(addPlatform_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 170, -1));

        findByPlatform.setText("Buscar");
        findByPlatform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findByPlatformActionPerformed(evt);
            }
        });
        getContentPane().add(findByPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 80, -1));

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(mainTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 13, -1, 460));

        addSerie_button.setText("Añadir serie");
        addSerie_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSerie_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(addSerie_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 170, -1));

        showSeries_button.setText("Todas las series");
        showSeries_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSeries_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(showSeries_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, -1));

        showMovies_button.setText("Todas las pelis");
        showMovies_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMovies_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(showMovies_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, -1));

        addMovie_button.setText("Añadir peliculas");
        addMovie_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovie_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(addMovie_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 170, -1));

        showPlatforms_button.setText("Info. de plataformas");
        showPlatforms_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPlatforms_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(showPlatforms_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
        if (manager.connection()) {
            component(true);
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo conectar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_connectActionPerformed

    private void disconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectActionPerformed
        manager.disconnection();
        component(false);
    }//GEN-LAST:event_disconnectActionPerformed

    private void restoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreActionPerformed
        manager.restoreDatabase();
        update();
    }//GEN-LAST:event_restoreActionPerformed

    private void addPlatform_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlatform_buttonActionPerformed
        addPlatform_frame.setVisible(true);
        addPlatform_frame.setSize(400, 300);
    }//GEN-LAST:event_addPlatform_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (manager.addPlatform(id_addPlatform.getText(), name_addPlatform.getText(), price_addPlatform.getText(), date_addPlatform.getText())) {
            id_addPlatform.setText("");
            name_addPlatform.setText("");
            price_addPlatform.setText("");
            date_addPlatform.setText("");
            addPlatform_frame.setVisible(false);
            update();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo añadir la plataforma revise la fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void findByPlatformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findByPlatformActionPerformed
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.getDataVector().removeAllElements();
        model.setColumnCount(4);
        model.setColumnIdentifiers(new Object[]{"Nombre", "Director", "Plataforma", "Fecha Salida"});
        for (int i = 0; i < manager.getSeriesandMovies(String.valueOf(platforma_comboBox_1.getSelectedItem())).length; i++) {
            model.addRow(new Object[]{manager.getSeriesandMovies(String.valueOf(platforma_comboBox_1.getSelectedItem()))[i][0], manager.getSeriesandMovies(String.valueOf(platforma_comboBox_1.getSelectedItem()))[i][1], manager.getSeriesandMovies(String.valueOf(platforma_comboBox_1.getSelectedItem()))[i][2], manager.getSeriesandMovies(String.valueOf(platforma_comboBox_1.getSelectedItem()))[i][3], manager.getSeriesandMovies(String.valueOf(platforma_comboBox_1.getSelectedItem()))[i][4]});
        }
    }//GEN-LAST:event_findByPlatformActionPerformed

    private void addSerie_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSerie_buttonActionPerformed
        addSerie_frame.setVisible(true);
        addSerie_frame.setSize(400, 300);
    }//GEN-LAST:event_addSerie_buttonActionPerformed

    private void accept_addPlatformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept_addPlatformActionPerformed
        if (manager.addSeries(id_addSerie.getText(), name_addSerie.getText(), director_addSerie.getText(), String.valueOf(platforma_comboBox_2.getSelectedItem()), date_addSerie.getText())) {
            id_addSerie.setText("");
            name_addSerie.setText("");
            director_addSerie.setText("");
            date_addSerie.setText("");
            platforma_comboBox_2.setSelectedIndex(0);
            addSerie_frame.setVisible(false);
            update();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo añadir la serie revise la fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accept_addPlatformActionPerformed

    private void accept_addMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept_addMovieActionPerformed
        if (manager.addMovie(id_addMovie.getText(), name_addMovie.getText(), director_addMovie.getText(), String.valueOf(platforma_comboBox_2.getSelectedItem()), date_addMovie.getText())){
            id_addMovie.setText("");
            name_addMovie.setText("");
            director_addMovie.setText("");
            date_addMovie.setText("");
            platforma_comboBox_3.setSelectedIndex(0);
            addMovie_frame.setVisible(false);
            update();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo añadir la serie revise la fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accept_addMovieActionPerformed

    private void showSeries_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSeries_buttonActionPerformed
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.getDataVector().removeAllElements();
        model.setColumnCount(4);
        model.setColumnIdentifiers(new Object[]{"Nombre", "Director", "Plataforma", "Fecha Salida"});
        for (int i = 0; i < manager.getSeries().length; i++) {
            model.addRow(new Object[]{manager.getSeries()[i][0], manager.getSeries()[i][1], manager.getSeries()[i][2], manager.getSeries()[i][3], manager.getSeries()[i][4]});
        }
    }//GEN-LAST:event_showSeries_buttonActionPerformed

    private void showMovies_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMovies_buttonActionPerformed
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.getDataVector().removeAllElements();
        model.setColumnCount(4);
        model.setColumnIdentifiers(new Object[]{"Nombre", "Director", "Plataforma", "Fecha Salida"});
        for (int i = 0; i < manager.getMovies().length; i++) {
            model.addRow(new Object[]{manager.getMovies()[i][0], manager.getMovies()[i][1], manager.getMovies()[i][2], manager.getMovies()[i][3], manager.getMovies()[i][4]});
        }
    }//GEN-LAST:event_showMovies_buttonActionPerformed

    private void addMovie_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovie_buttonActionPerformed
        addMovie_frame.setVisible(true);
        addMovie_frame.setSize(400, 300);
    }//GEN-LAST:event_addMovie_buttonActionPerformed

    private void showPlatforms_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPlatforms_buttonActionPerformed
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.getDataVector().removeAllElements();
        model.setColumnCount(4);
        model.setColumnIdentifiers(new Object[]{"Nombre", "Precio", "Fecha salida", "Años en el aire"});
        for (int i = 0; i < manager.getPlatforms().length; i++) {
            model.addRow(new Object[]{manager.getPlatforms()[i][0], manager.getPlatforms()[i][1]+" €", manager.getPlatforms()[i][2], manager.getPlatforms()[i][3], manager.getPlatforms()[i][4]+" años"});
        }
    }//GEN-LAST:event_showPlatforms_buttonActionPerformed

    public void update() {
        component(false);
        component(true);
    }

    public void component(Boolean state) {
        connect.setEnabled(!state);
        disconnect.setEnabled(state);
        platforma_comboBox_1.setEnabled(state);
        restore.setEnabled(state);
        addPlatform_button.setEnabled(state);
        findByPlatform.setEnabled(state);
        addSerie_button.setEnabled(state);
        showSeries_button.setEnabled(state);
        showMovies_button.setEnabled(state);
        showPlatforms_button.setEnabled(state);
        addMovie_button.setEnabled(state);
        if (state) {
            platforma_comboBox_1.addItem("");
            platforma_comboBox_2.addItem("");
            platforma_comboBox_3.addItem("");
            for (int i = 0; i < manager.getPlatforms().length; i++) {
                platforma_comboBox_1.addItem(manager.getPlatforms()[i][0]);
                platforma_comboBox_2.addItem(manager.getPlatforms()[i][0]);
                platforma_comboBox_3.addItem(manager.getPlatforms()[i][0]);
            }
        } else {
            for (int i = platforma_comboBox_1.getItemCount() - 1; i >= 0; i--) {
                platforma_comboBox_1.removeItemAt(i);
                platforma_comboBox_2.removeItemAt(i);
                platforma_comboBox_3.removeItemAt(i);
                
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept_addMovie;
    private javax.swing.JButton accept_addPlatform;
    private javax.swing.JButton addMovie_button;
    private javax.swing.JFrame addMovie_frame;
    private javax.swing.JButton addPlatform_button;
    private javax.swing.JFrame addPlatform_frame;
    private javax.swing.JButton addSerie_button;
    private javax.swing.JFrame addSerie_frame;
    private javax.swing.JButton connect;
    private javax.swing.JTextField date_addMovie;
    private javax.swing.JTextField date_addPlatform;
    private javax.swing.JTextField date_addSerie;
    private javax.swing.JTextField director_addMovie;
    private javax.swing.JTextField director_addSerie;
    private javax.swing.JButton disconnect;
    private javax.swing.JButton findByPlatform;
    private javax.swing.JTextField id_addMovie;
    private javax.swing.JTextField id_addPlatform;
    private javax.swing.JTextField id_addSerie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    private javax.swing.JTextField name_addMovie;
    private javax.swing.JTextField name_addPlatform;
    private javax.swing.JTextField name_addSerie;
    private javax.swing.JComboBox<String> platforma_comboBox_1;
    private javax.swing.JComboBox<String> platforma_comboBox_2;
    private javax.swing.JComboBox<String> platforma_comboBox_3;
    private javax.swing.JTextField price_addPlatform;
    private javax.swing.JButton restore;
    private javax.swing.JButton showMovies_button;
    private javax.swing.JButton showPlatforms_button;
    private javax.swing.JButton showSeries_button;
    // End of variables declaration//GEN-END:variables
}
